<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKabtiul\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKabtiul/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerKabtiul.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerKabtiul\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerKabtiul\appProdProjectContainer(array(
    'container.build_hash' => 'Kabtiul',
    'container.build_id' => 'be17814e',
    'container.build_time' => 1540838015,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerKabtiul');
